import {Translation} from "../Translation";

const CS: Translation = {
    this_lang: "Czech",
    loading: "Načítání...",
    redirecting: "Přesměrování...",
    success: "Hotovo",
    error: "Error",
    errorOccurred: "Objevil se error. Prosím zkus to později.",
    servers: "Servery",
    warnings: "Varování",
    createWarning: "Vytvořit Varování",
    ipBans: "IP Bany",
    createIPBan: "Vytvořit IP Ban",
    bans: "Bany",
    createBan: "Vytvořit Ban",
    playerTitle: "Bany a Varování pro ",
    issuerTitle: "Bany a Varování vydány hráčem ",
    idVal: "ID:",
    issuerVal: "Vydavatel:",
    playerVal: "Hráč:",
    reasonVal: "Důvod:",
    issuedVal: "Vydáno:",
    expiresVal: "Vyprší:",
    serverConsole: "Server Console",
    unknown: "Neznámý",
    unpardon: "Un-Pardon",
    unpardonSuccess: "Successfully un-pardoned ban!",
    pardon: "Prominout",
    pardonSuccess: "Úspěšně prominut ban!",
    delete: "Vymazat",
    deleteSuccess: "Úspěšně vymazáno varování/ban!",
    confirmTitle: "Jsi si jistý?",
    confirmMessage: "Prosím potvrď, že chceš dokončit tuto akci.",
    confirm: "Potvrdit",
    cancel: "Zrušit",
    invalidIP: "Neplatná IP",
    invalidIPDesc: "Zadaná ip je neplatná. IP můžou být IPv4 a IPv6.",
    invalidID: "Neplatné ID",
    invalidIDDesc: "Zadané id je neplatné. ID můžou být steam, discord, nebo northwood ID a musí končit pomocí @steam/@discord/@northwood.",
    invalidDuration: "Neplatná délka",
    invalidDurationDesc: "Zadaná délka je neplatná. Délka funguje stejně jako ve hře.",
    createBanSuccess: "Úspěšně vytvořen ban!",
    createWarningSuccess: "Úspěšně vytvořeno varování!",
    ip: "IP",
    ipHint: "Prosím zadej hráčovu IP.",
    id: "ID",
    idHint: "Prosím zadej hráčovo ID.",
    duration: "Délka",
    durationHint: "Prosím zadej délku banu.",
    reason: "Důvod",
    reasonHint: "Prosím zadej důvod varování/banu.",
    submit: "Potvrdit",
    edit: "Upravit",
    editBan: "Upravit Ban",
    editBanSuccess: "Ban úspěšně upraven!",
    editWarning: "Upravit Varování",
    editWarningSuccess: "Varování úspěšně upraveno!",
    profile: "Profil",
    language: "Jazyk",
    logout: "Odhlásit se",
    searchHint: "Hledat...",
    playtime: "Odehraný čas:",
    lastSeen: "Naposledy viděn:",
    myPlaytime: "My Playtime",
    playtimeTitle: "Playtime"
}

export default CS;
