import {Translation} from "../Translation";

const CS: Translation = {
    this_lang: "Czech",
    loading: "Načítání...",
    redirecting: "Přesměrování...",
    success: "Hotovo",
    error: "Error",
    errorOccurred: "Objevil se error. Prosím zkus to později.",
    servers: "Servery",
    warnings: "Varování",
    createWarning: "Vytvořit Varování",
    ipBans: "IP Bany",
    createIPBan: "Vytvořit IP Ban",
    bans: "Bany",
    createBan: "Vytvořit Ban",
    playerTitle: "Bany a Varování pro ",
    issuerTitle: "Bany a Varování vydány hráčem ",
    idVal: "ID:",
    issuerVal: "Vydavatel:",
    playerVal: "Hráč:",
    reasonVal: "Důvod:",
    issuedVal: "Vydáno:",
    expiresVal: "Vyprší:",
    serverConsole: "Server Console",
    unknown: "Neznámý",
    unpardon: "Un-Pardon",
    unpardonSuccess: "Successfully un-pardoned ban!",
    pardon: "Prominout",
    pardonSuccess: "Úspěšně prominut ban!",
    delete: "Vymazat",
    deleteSuccess: "Úspěšně vymazáno varování/ban!",
    confirmTitle: "Jsi si jistý?",
    confirmMessage: "Prosím potvrď, že chceš dokončit tuto akci.",
    confirm: "Potvrdit",
    cancel: "Zrušit",
    invalidIP: "Neplatná IP",
    invalidIPDesc: "Zadaná ip je neplatná. IP můžou být IPv4 a IPv6.",
    invalidID: "Neplatné ID",
    invalidIDDesc: "Zadané id je neplatné. ID můžou být steam, discord, nebo northwood ID a musí končit pomocí @steam/@discord/@northwood.",
    invalidDuration: "Neplatná délka",
    invalidDurationDesc: "Zadaná délka je neplatná. Délka funguje stejně jako ve hře.",
    createBanSuccess: "Úspěšně vytvořen ban!",
    createWarningSuccess: "Úspěšně vytvořeno varování!",
    ip: "IP",
    ipHint: "Prosím zadej hráčovu IP.",
    id: "ID",
    idHint: "Prosím zadej hráčovo ID.",
    duration: "Délka",
    durationHint: "Prosím zadej délku banu.",
    reason: "Důvod",
    reasonHint: "Prosím zadej důvod varování/banu.",
    submit: "Potvrdit",
    edit: "Upravit",
    editBan: "Upravit Ban",
    editBanSuccess: "Ban úspěšně upraven!",
    editWarning: "Upravit Varování",
    editWarningSuccess: "Varování úspěšně upraveno!",
    profile: "Profil",
    language: "Jazyk",
    logout: "Odhlásit se",
    searchHint: "Hledat...",
    playtime: "Odehraný čas:",
    lastSeen: "Naposledy viděn:",
    myPlaytime: "My Playtime",
    playtimeTitle: "Playtime",
    staffPlaytime: "Staff Playtime",
    lookupPlayer: "Lookup Player",
    lookupIssuer: "Lookup Issuer",
    reports: "Reports",
    warning: "Warning",
    ban: "Ban",
    report: "Report",
    cheaterReport: "Cheater Report",
    players: "Players",
    name: "Name",
    names: "Names",
    lastJoin: "Last Join",
    lastLeave: "Last Leave",
    firstJoin: "First Join",
    firstLeave: "First Leave",
    myServers: "My Servers",
    viewSecret: "View Secret",
    changeName: "Change Name",
    resetSecret: "Reset Secret",
    viewSecretMsg1: "This server's secret is below. Keep it private and reset it immediately if anyone gets access to it!",
    viewSecretMsg2: "To connect this server to your game server, run the following command in your server console:",
    changeNameNewName: "New Name",
    resetSecretMsg: "Resetting your server's secret will disconnect it from its connected server. Make sure you put in the new secret after resetting it.",
    changeNameSuccess: "Successfully changed name!",
    resetSecretSuccess: "Successfully reset secret!",
    createServer: "Create Server",
    createServerMsg: "Once you create a server, click the View Secret button to connect it to your game server.",
    createServerSuccess: "Successfully created server!",
    linkToDiscord: "Link to Discord",
    linkToDiscordMsg1: "This server's ID is below. It can be used to link this server to your discord server.",
    linkToDiscordMsg2: "To link this server to your discord server, run the following command in your discord server:",
    linkToDiscordCmd: "/link",
}

export default CS;
