import {Translation} from "../Translation";

const EN: Translation = {
    this_lang: "English",
    loading: "Loading...",
    redirecting: "Redirecting...",
    success: "Success",
    error: "Error",
    errorOccurred: "An error occurred. Please try again.",
    servers: "Servers",
    warnings: "Warnings",
    createWarning: "Create Warning",
    ipBans: "IP Bans",
    createIPBan: "Create IP Ban",
    bans: "Bans",
    createBan: "Create Ban",
    playerTitle: "Bans and Warnings for ",
    issuerTitle: "Bans and Warnings issued by ",
    idVal: "ID:",
    issuerVal: "Issuer:",
    playerVal: "Player:",
    reasonVal: "Reason:",
    issuedVal: "Issued:",
    expiresVal: "Expires:",
    serverConsole: "Server Console",
    unknown: "Unknown",
    unpardon: "Un-Pardon",
    unpardonSuccess: "Successfully un-pardoned ban!",
    pardon: "Pardon",
    pardonSuccess: "Successfully pardoned ban!",
    delete: "Delete",
    deleteSuccess: "Successfully deleted warning/ban!",
    confirmTitle: "Are you sure?",
    confirmMessage: "Please confirm that you want to complete this action.",
    confirm: "Confirm",
    cancel: "Cancel",
    invalidIP: "Invalid IP",
    invalidIPDesc: "The input ip is invalid. IPs can be IPv4 and IPv6.",
    invalidID: "Invalid ID",
    invalidIDDesc: "The input id is invalid. IDs can be steam, discord, and northwood IDs, and must end in @steam/@discord/@northwood.",
    invalidDuration: "Invalid Duration",
    invalidDurationDesc: "The input duration is invalid. Durations strings appear exactly as they do in-game.",
    createBanSuccess: "Successfully created ban!",
    createWarningSuccess: "Successfully created warning!",
    ip: "IP",
    ipHint: "Please enter the player's IP.",
    id: "ID",
    idHint: "Please enter the player's ID.",
    duration: "Duration",
    durationHint: "Please enter the duration of the ban.",
    reason: "Reason",
    reasonHint: "Please enter the reason for the warning/ban.",
    submit: "Submit",
    edit: "Edit",
    editBan: "Edit Ban",
    editBanSuccess: "Successfully edited ban!",
    editWarning: "Edit Warning",
    editWarningSuccess: "Successfully edited warning!",
    profile: "Profile",
    language: "Language",
    logout: "Logout",
    searchHint: "Search...",
    playtime: "Playtime:",
    lastSeen: "Last seen:",
    myPlaytime: "My Playtime",
    playtimeTitle: "Playtime",
    staffPlaytime: "Staff Playtime",
    lookupPlayer: "Lookup Player",
    lookupIssuer: "Lookup Issuer",
    reports: "Reports",
    warning: "Warning",
    ban: "Ban",
    report: "Report",
    cheaterReport: "Cheater Report",
    players: "Players",
    name: "Name",
    names: "Names",
    lastJoin: "Last Join",
    lastLeave: "Last Leave",
    firstJoin: "First Join",
    firstLeave: "First Leave",
    myServers: "My Servers",
    viewSecret: "View Secret",
    changeName: "Change Name",
    resetSecret: "Reset Secret",
    viewSecretMsg1: "This server's secret is below. Keep it private and reset it immediately if anyone gets access to it!",
    viewSecretMsg2: "To connect this server to your game server, run the following command in your server console:",
    changeNameNewName: "New Name",
    resetSecretMsg: "Resetting your server's secret will disconnect it from its connected server. Make sure you put in the new secret after resetting it.",
    changeNameSuccess: "Successfully changed name!",
    resetSecretSuccess: "Successfully reset secret!",
    createServer: "Create Server",
    createServerMsg: "Once you create a server, click the View Secret button to connect it to your game server.",
    createServerSuccess: "Successfully created server!",
    linkToDiscord: "Link to Discord",
    linkToDiscordMsg1: "This server's ID is below. It can be used to link this server to your discord server.",
    linkToDiscordMsg2: "To link this server to your discord server, run the following command in your discord server:",
    linkToDiscordCmd: "/link serverid:",
}

export default EN;
