import {Translation} from "../Translation";

const IT: Translation = {
    this_lang: "Italiano",
    loading: "Caricamento...",
    redirecting: "Reindirizzamento...",
    success: "Successo",
    error: "Errore",
    errorOccurred: "C'è stato uno errore. Riprova.",
    servers: "Server",
    warnings: "Warn",
    createWarning: "Crea warn",
    ipBans: "IP Ban",
    createIPBan: "Crea IP Ban",
    bans: "Ban",
    createBan: "Crea Ban",
    playerTitle: "Ban e warn di ",
    issuerTitle: "Ban e warn dati da ",
    idVal: "ID:",
    issuerVal: "Dato da:",
    playerVal: "Giocatore:",
    reasonVal: "Ragione:",
    issuedVal: "Dato il giorno:",
    expiresVal: "Scadenza:",
    serverConsole: "Console del server",
    unknown: "Sconosciuto",
    unpardon: "Non revocare ban",
    unpardonSuccess: "Ban non revocato!",
    pardon: "Revoca ban",
    pardonSuccess: "Ban revocato!",
    delete: "Cancella",
    deleteSuccess: "Warn/ban cancellato!",
    confirmTitle: "Sei sicuro?",
    confirmMessage: "Per favore, conferma di voler annullare questa azione.",
    confirm: "Conferma",
    cancel: "Annulla",
    invalidIP: "IP non valido",
    invalidIPDesc: "L'IP non è valido. L'IP può essere solo IPv4 o IPv6.",
    invalidID: "ID non valido",
    invalidIDDesc: "L'ID non è valido. Gli ID possono essere quello di steam, di discord o un ID della Northwood, i quali devono rispettivamente finire con @steam/@discord/@northwood.",
    invalidDuration: "Durata non valida",
    invalidDurationDesc: "La durata non è valida. Le durate sono esattamente come quelle che ci sono in gioco.",
    createBanSuccess: "Ban effettuato con successo!",
    createWarningSuccess: "Warn effettuato con successo!",
    ip: "IP",
    ipHint: "Inserisci l'IP del giocatore.",
    id: "ID",
    idHint: "Inserisci l'ID del giocatore.",
    duration: "Durata",
    durationHint: "Inserisci la durata del ban.",
    reason: "Ragione",
    reasonHint: "Inserisci la ragione del warn/ban.",
    submit: "Invia",
    edit: "Modifica",
    editBan: "Modifica ban",
    editBanSuccess: "Ban modificato!",
    editWarning: "Modifica warn",
    editWarningSuccess: "Warn modificato!",
    profile: "Profilo",
    language: "Lingua",
    logout: "Esegui il logout",
    searchHint: "Ricerca...",
    playtime: "Tempo di gioco:",
    lastSeen: "Ultima volta online:",
    myPlaytime: "My Playtime",
    playtimeTitle: "Playtime",
    staffPlaytime: "Staff Playtime",
    lookupPlayer: "Lookup Player",
    lookupIssuer: "Lookup Issuer",
    reports: "Reports",
    warning: "Warning",
    ban: "Ban",
    report: "Report",
    cheaterReport: "Cheater Report",
    players: "Players",
    name: "Name",
    names: "Names",
    lastJoin: "Last Join",
    lastLeave: "Last Leave",
    firstJoin: "First Join",
    firstLeave: "First Leave",
    myServers: "My Servers",
    viewSecret: "View Secret",
    changeName: "Change Name",
    resetSecret: "Reset Secret",
    viewSecretMsg1: "This server's secret is below. Keep it private and reset it immediately if anyone gets access to it!",
    viewSecretMsg2: "To connect this server to your game server, run the following command in your server console:",
    changeNameNewName: "New Name",
    resetSecretMsg: "Resetting your server's secret will disconnect it from its connected server. Make sure you put in the new secret after resetting it.",
    changeNameSuccess: "Successfully changed name!",
    resetSecretSuccess: "Successfully reset secret!",
    createServer: "Create Server",
    createServerMsg: "Once you create a server, click the View Secret button to connect it to your game server.",
    createServerSuccess: "Successfully created server!",
    linkToDiscord: "Link to Discord",
    linkToDiscordMsg1: "This server's ID is below. It can be used to link this server to your discord server.",
    linkToDiscordMsg2: "To link this server to your discord server, run the following command in your discord server:",
    linkToDiscordCmd: "/link serverid:",
}

export default IT;
