import {Translation} from "../Translation";

const PL: Translation = {
    this_lang: "Polski",
    loading: "Ładowanie...",
    redirecting: "Przekierowywanie...",
    success: "Sukces",
    error: "Błąd",
    errorOccurred: "Wystąpił błąd. Spróbuj ponownie.",
    servers: "Serwery",
    warnings: "Ostrzeżenia",
    createWarning: "Stwórz ostrzeżenie",
    ipBans: "Bany na IP",
    createIPBan: "Stwórz Bana na IP",
    bans: "Bany",
    createBan: "Stwórz Bana",
    playerTitle: "Bany i ostrzeżenia dla ",
    issuerTitle: "Bany i ostrzeżenia nadane przez ",
    idVal: "ID:",
    issuerVal: "Administrator:",
    playerVal: "Gracz:",
    reasonVal: "Powód:",
    issuedVal: "Nadany:",
    expiresVal: "Wygasa:",
    serverConsole: "Konsola serwera",
    unknown: "Nieznany",
    unpardon: "Od-Ułaskaw",
    unpardonSuccess: "Pomyślnie od-ułaskawiono!",
    pardon: "Ułaskaw",
    pardonSuccess: "Pomyślnie ułaskawiono!",
    delete: "Usuń",
    deleteSuccess: "Pomyślnie usunięto ostrzeżenie/bana!",
    confirmTitle: "Czy jesteś pewien?",
    confirmMessage: "Podwierdź, że chcesz wykonać tą czynność.",
    confirm: "Potwierdź",
    cancel: "Anuluj",
    invalidIP: "Nieprawidłowe IP",
    invalidIPDesc: "Wprowadzone IP jest nieprawidłowe. IP może być IPv4 lub IPv6.",
    invalidID: "Nieprawidłowe ID",
    invalidIDDesc: "Wprowadzone ID jest nieprawidłowe. Może być to Steam ID, Discord ID lub Northwood ID i musi być zakończone @steam/@discord/@northwood.",
    invalidDuration: "Nieprawidłowy czas",
    invalidDurationDesc: "Wprowadzony format czasu jest nieprawidłowy. Prawidłowe formaty czasu, są takie same, jak w grze",
    createBanSuccess: "Pomyślnie utworzono bana!",
    createWarningSuccess: "Pomyślnie utworzono ostrzeżenie!",
    ip: "IP",
    ipHint: "Podaj IP gracza.",
    id: "ID",
    idHint: "Podaj ID gracza.",
    duration: "Długość",
    durationHint: "Podaj długość bana.",
    reason: "Powód",
    reasonHint: "Podaj powód ostrzeżenia/bana.",
    submit: "Zatwierdź",
    edit: "Edytuj",
    editBan: "Edytuj bana",
    editBanSuccess: "Pomyślnie edytowano bana!",
    editWarning: "Edytuj ostrzeżenie",
    editWarningSuccess: "Pomyślnie edytowano ostrzeżenie!",
    profile: "Profil",
    language: "Język",
    logout: "Wyloguj",
    searchHint: "Szukaj...",
    playtime: "Czas gry:",
    lastSeen: "Ostatnio widziany:"
}

export default PL;
