import {Translation} from "../Translation";

const PL: Translation = {
    this_lang: "Polski",
    loading: "Ładowanie...",
    redirecting: "Przekierowywanie...",
    success: "Sukces",
    error: "Błąd",
    errorOccurred: "Wystąpił błąd. Spróbuj ponownie.",
    servers: "Serwery",
    warnings: "Ostrzeżenia",
    createWarning: "Stwórz ostrzeżenie",
    ipBans: "Bany na IP",
    createIPBan: "Stwórz Bana na IP",
    bans: "Bany",
    createBan: "Stwórz Bana",
    playerTitle: "Bany i ostrzeżenia dla ",
    issuerTitle: "Bany i ostrzeżenia nadane przez ",
    idVal: "ID:",
    issuerVal: "Administrator:",
    playerVal: "Gracz:",
    reasonVal: "Powód:",
    issuedVal: "Nadany:",
    expiresVal: "Wygasa:",
    serverConsole: "Konsola serwera",
    unknown: "Nieznany",
    unpardon: "Od-Ułaskaw",
    unpardonSuccess: "Pomyślnie od-ułaskawiono!",
    pardon: "Ułaskaw",
    pardonSuccess: "Pomyślnie ułaskawiono!",
    delete: "Usuń",
    deleteSuccess: "Pomyślnie usunięto ostrzeżenie/bana!",
    confirmTitle: "Czy jesteś pewien?",
    confirmMessage: "Podwierdź, że chcesz wykonać tą czynność.",
    confirm: "Potwierdź",
    cancel: "Anuluj",
    invalidIP: "Nieprawidłowe IP",
    invalidIPDesc: "Wprowadzone IP jest nieprawidłowe. IP może być IPv4 lub IPv6.",
    invalidID: "Nieprawidłowe ID",
    invalidIDDesc: "Wprowadzone ID jest nieprawidłowe. Może być to Steam ID, Discord ID lub Northwood ID i musi być zakończone @steam/@discord/@northwood.",
    invalidDuration: "Nieprawidłowy czas",
    invalidDurationDesc: "Wprowadzony format czasu jest nieprawidłowy. Prawidłowe formaty czasu, są takie same, jak w grze",
    createBanSuccess: "Pomyślnie utworzono bana!",
    createWarningSuccess: "Pomyślnie utworzono ostrzeżenie!",
    ip: "IP",
    ipHint: "Podaj IP gracza.",
    id: "ID",
    idHint: "Podaj ID gracza.",
    duration: "Długość",
    durationHint: "Podaj długość bana.",
    reason: "Powód",
    reasonHint: "Podaj powód ostrzeżenia/bana.",
    submit: "Zatwierdź",
    edit: "Edytuj",
    editBan: "Edytuj bana",
    editBanSuccess: "Pomyślnie edytowano bana!",
    editWarning: "Edytuj ostrzeżenie",
    editWarningSuccess: "Pomyślnie edytowano ostrzeżenie!",
    profile: "Profil",
    language: "Język",
    logout: "Wyloguj",
    searchHint: "Szukaj...",
    playtime: "Czas gry:",
    lastSeen: "Ostatnio widziany:",
    myPlaytime: "Mój czas gry",
    playtimeTitle: "Czas gry",
    staffPlaytime: "Czas gry Administracji",
    lookupPlayer: "Sprawdź Gracza",
    lookupIssuer: "Sprawdź Administratora",
    reports: "Zgłoszenia",
    warning: "Ostrzeżenie",
    ban: "Ban",
    report: "Zgłoszenie",
    cheaterReport: "Zgłoszenie Cheatera",
    players: "Players",
    name: "Name",
    names: "Names",
    lastJoin: "Last Join",
    lastLeave: "Last Leave",
    firstJoin: "First Join",
    firstLeave: "First Leave",
    myServers: "My Servers",
    viewSecret: "View Secret",
    changeName: "Change Name",
    resetSecret: "Reset Secret",
    viewSecretMsg1: "This server's secret is below. Keep it private and reset it immediately if anyone gets access to it!",
    viewSecretMsg2: "To connect this server to your game server, run the following command in your server console:",
    changeNameNewName: "New Name",
    resetSecretMsg: "Resetting your server's secret will disconnect it from its connected server. Make sure you put in the new secret after resetting it.",
    changeNameSuccess: "Successfully changed name!",
    resetSecretSuccess: "Successfully reset secret!",
    createServer: "Create Server",
    createServerMsg: "Once you create a server, click the View Secret button to connect it to your game server.",
    createServerSuccess: "Successfully created server!",
    linkToDiscord: "Link to Discord",
    linkToDiscordMsg1: "This server's ID is below. It can be used to link this server to your discord server.",
    linkToDiscordMsg2: "To link this server to your discord server, run the following command in your discord server:",
    linkToDiscordCmd: "/link serverid:",
}

export default PL;
