import {Translation} from "../Translation";

const RU: Translation = {
    this_lang: "Русский",
    loading: "Загрузка...",
    redirecting: "Перенаправление...",
    success: "Успех",
    error: "Ошибка",
    errorOccurred: "Произошла ошибка. Попробуйте еще раз.",
    servers: "Серверы",
    warnings: "Предупреждения",
    createWarning: "Создать предупреждение",
    ipBans: "Баны IP",
    createIPBan: "Создать бан IP",
    bans: "Баны",
    createBan: "Создать бан",
    playerTitle: "Баны и предупреждения, выданные игроку ",
    issuerTitle: "Баны и предупреждения, выданные администратором ",
    idVal: "ID:",
    issuerVal: "Выдал:",
    playerVal: "Игрок:",
    reasonVal: "Причина:",
    issuedVal: "Выдано:",
    expiresVal: "Истекает:",
    serverConsole: "Консоль сервера",
    unknown: "Неизвестно",
    unpardon: "Забанить",
    unpardonSuccess: "Игрок успешно забанен!",
    pardon: "Разбанить",
    pardonSuccess: "Игрок успешно разбанен!",
    delete: "Удалить",
    deleteSuccess: "Предупреждение/бан успешно удален!",
    confirmTitle: "Вы уверены?",
    confirmMessage: "Подтвердите, что вы хотите выполнить данное действие.",
    confirm: "Подтвердить",
    cancel: "Отмена",
    invalidIP: "Недопустимый IP",
    invalidIPDesc: "Принимается IPv4 или IPv6.",
    invalidID: "Недопустимый ID",
    invalidIDDesc: "Принимаются SteamID64, DiscordID и NorthwoodID. Они должны оканчиваться на @steam/@discord/@northwood.",
    invalidDuration: "Недопустимая длительность",
    invalidDurationDesc: "Принимается формат длительности, который используется в игре.",
    createBanSuccess: "Бан успешно создан!",
    createWarningSuccess: "Предупреждение успешно создано!",
    ip: "IP",
    ipHint: "Укажите IP-адрес игрока.",
    id: "ID",
    idHint: "Укажите ID игрока.",
    duration: "Длительность",
    durationHint: "Укажите длительность бана.",
    reason: "Причина",
    reasonHint: "Укажите причину предупреждения/бана.",
    submit: "Отправить",
    edit: "Изменить",
    editBan: "Изменить бан",
    editBanSuccess: "Бан успешно изменен!",
    editWarning: "Изменить предупреждение",
    editWarningSuccess: "Предупреждение успешно изменено!",
    profile: "Профиль",
    language: "Язык",
    logout: "Выход",
    searchHint: "Поиск...",
    playtime: "Наигранное время:",
    lastSeen: "Последний вход:",
    myPlaytime: "Ваше наигранное время",
    playtimeTitle: "Наигранное время",
    staffPlaytime: "Наигранное время администраторов",
    lookupPlayer: "История игрока",
    lookupIssuer: "История администратора",
    reports: "Жалобы",
    warning: "Предупреждение",
    ban: "Бан",
    report: "Жалоба",
    cheaterReport: "Жалоба на читерство",
    players: "Игроки",
    name: "Никнейм",
    names: "Никнеймы",
    lastJoin: "Последний вход",
    lastLeave: "Последний выход",
    firstJoin: "Первый вход",
    firstLeave: "Первый выход",
    myServers: "My Servers",
    viewSecret: "View Secret",
    changeName: "Change Name",
    resetSecret: "Reset Secret",
    viewSecretMsg1: "This server's secret is below. Keep it private and reset it immediately if anyone gets access to it!",
    viewSecretMsg2: "To connect this server to your game server, run the following command in your server console:",
    changeNameNewName: "New Name",
    resetSecretMsg: "Resetting your server's secret will disconnect it from its connected server. Make sure you put in the new secret after resetting it.",
    changeNameSuccess: "Successfully changed name!",
    resetSecretSuccess: "Successfully reset secret!",
    createServer: "Create Server",
    createServerMsg: "Once you create a server, click the View Secret button to connect it to your game server.",
    createServerSuccess: "Successfully created server!",
    linkToDiscord: "Link to Discord",
    linkToDiscordMsg1: "This server's ID is below. It can be used to link this server to your discord server.",
    linkToDiscordMsg2: "To link this server to your discord server, run the following command in your discord server:",
    linkToDiscordCmd: "/link serverid:",
}

export default RU;
