import {Translation} from "../Translation";

const TH: Translation = {
    this_lang: "ไทย",
    loading: "กำลังโหลด...",
    redirecting: "Redirecting...",
    success: "สำเร็จ",
    error: "Error",
    errorOccurred: "เกิดข้อผิดพลาดขึ้น กรุณาลองอีกครั้ง",
    servers: "เซิร์ฟเวอร์",
    warnings: "การเตือน",
    createWarning: "สร้างการเตือนใหม่",
    ipBans: "การแบนไอพี",
    createIPBan: "แบนไอพีใหม่",
    bans: "การแบน",
    createBan: "สร้างการแบนใหม่",
    playerTitle: "ประวัติการแบนและเตือนของ ",
    issuerTitle: "ประวัติการแบนและเตือนโดย ",
    idVal: "ไอดี:",
    issuerVal: "คนจัดการ:",
    playerVal: "ผู้เล่น:",
    reasonVal: "เหตุผล:",
    issuedVal: "เวลา:",
    expiresVal: "จะหายใน:",
    serverConsole: "เซิร์ฟเวอร์ คอนโซล",
    unknown: "ไม่พบข้อมูล",
    unpardon: "ยกเลิกการให้อภัย",
    unpardonSuccess: "ยกเลิกให้อภัยสำเร็จ !",
    pardon: "ให้อภัย",
    pardonSuccess: "ให้อภัยสำเร็จ !",
    delete: "ลบ",
    deleteSuccess: "ลบการเตือน/แบนสำเร็จ !",
    confirmTitle: "คุณแน่ใจนะ?",
    confirmMessage: "กรุณายืนยันอีกครั้ง",
    confirm: "ยืนยัน",
    cancel: "ยกเลิก",
    invalidIP: "ไอพีไม่ถูกต้อง",
    invalidIPDesc: "ไอพีที่คุณกรอกนั้นไม่ถูกต้อง โดยไอพีสามารถเป็นได้ทั้งแบบ IPv4 และ IPv6",
    invalidID: "ไอดีไม่ถูกต้อง",
    invalidIDDesc: "ไอดีที่ได้รับนั้นไม่ถูกต้อง โดยไอดีสามารถเป็นของ steam discord หรือ northwood และต้องลงท้ายด้วย @steam/@discord/@northwood",
    invalidDuration: "ระยะเวลาไม่ถูกต้อง",
    invalidDurationDesc: "ระยะเวลาที่กรอกมาไม่ถูกต้อง คุณต้องใส่ระยะเวลาเหมือนการแบนในเกม",
    createBanSuccess: "เพิ่มการแบนสำเร็จ !",
    createWarningSuccess: "เพิ่มการเตือนสำเร็จ !",
    ip: "ไอพี",
    ipHint: "กรุณากรอกไอพีของผู้เล่น",
    id: "ไอดี",
    idHint: "กรุณากรอกไอดีของผู้เล่น",
    duration: "ระยะเวลา",
    durationHint: "กรุณากรอกระยะเวลาการแบน",
    reason: "เหตุผล",
    reasonHint: "กรุณากรอกเหตุผลการเตือน/แบน",
    submit: "ยืนยัน",
    edit: "แก้ไข",
    editBan: "แก้ไขการแบน",
    editBanSuccess: "แก้ไขการแบนสำเร็จ !",
    editWarning: "แก้ไขการเตือน",
    editWarningSuccess: "แก้ไขการเตือนสำเร็จ !",
    profile: "โปรไฟล์",
    language: "ภาษา",
    logout: "ล็อกเอาท์",
    searchHint: "ค้นหา...",
    playtime: "ระยะเวลาที่เล่น:",
    lastSeen: "พบล่าสุด:",
    myPlaytime: "เวลาที่เล่นไปของคุณ",
    playtimeTitle: "ระยะเวลาการเล่น",
    staffPlaytime: "เวลาที่เล่นไปของสตาฟ",
    lookupPlayer: "ค้นหาผู้เล่น",
    lookupIssuer: "ค้นหาคนลงโทษ"
}

export default TH;
