import {Translation} from "../Translation";

const TH: Translation = {
    this_lang: "ไทย",
    loading: "กำลังโหลด...",
    redirecting: "Redirecting...",
    success: "สำเร็จ",
    error: "Error",
    errorOccurred: "เกิดข้อผิดพลาดขึ้น กรุณาลองอีกครั้ง",
    servers: "เซิร์ฟเวอร์",
    warnings: "การเตือน",
    createWarning: "สร้างการเตือนใหม่",
    ipBans: "การแบนไอพี",
    createIPBan: "แบนไอพีใหม่",
    bans: "การแบน",
    createBan: "สร้างการแบนใหม่",
    playerTitle: "ประวัติการแบนและเตือนของ ",
    issuerTitle: "ประวัติการแบนและเตือนโดย ",
    idVal: "ไอดี:",
    issuerVal: "คนจัดการ:",
    playerVal: "ผู้เล่น:",
    reasonVal: "เหตุผล:",
    issuedVal: "เวลา:",
    expiresVal: "จะหายใน:",
    serverConsole: "เซิร์ฟเวอร์ คอนโซล",
    unknown: "ไม่พบข้อมูล",
    unpardon: "ยกเลิกการให้อภัย",
    unpardonSuccess: "ยกเลิกให้อภัยสำเร็จ !",
    pardon: "ให้อภัย",
    pardonSuccess: "ให้อภัยสำเร็จ !",
    delete: "ลบ",
    deleteSuccess: "ลบการเตือน/แบนสำเร็จ !",
    confirmTitle: "คุณแน่ใจนะ?",
    confirmMessage: "กรุณายืนยันอีกครั้ง",
    confirm: "ยืนยัน",
    cancel: "ยกเลิก",
    invalidIP: "ไอพีไม่ถูกต้อง",
    invalidIPDesc: "ไอพีที่คุณกรอกนั้นไม่ถูกต้อง โดยไอพีสามารถเป็นได้ทั้งแบบ IPv4 และ IPv6",
    invalidID: "ไอดีไม่ถูกต้อง",
    invalidIDDesc: "ไอดีที่ได้รับนั้นไม่ถูกต้อง โดยไอดีสามารถเป็นของ steam discord หรือ northwood และต้องลงท้ายด้วย @steam/@discord/@northwood",
    invalidDuration: "ระยะเวลาไม่ถูกต้อง",
    invalidDurationDesc: "ระยะเวลาที่กรอกมาไม่ถูกต้อง คุณต้องใส่ระยะเวลาเหมือนการแบนในเกม",
    createBanSuccess: "เพิ่มการแบนสำเร็จ !",
    createWarningSuccess: "เพิ่มการเตือนสำเร็จ !",
    ip: "ไอพี",
    ipHint: "กรุณากรอกไอพีของผู้เล่น",
    id: "ไอดี",
    idHint: "กรุณากรอกไอดีของผู้เล่น",
    duration: "ระยะเวลา",
    durationHint: "กรุณากรอกระยะเวลาการแบน",
    reason: "เหตุผล",
    reasonHint: "กรุณากรอกเหตุผลการเตือน/แบน",
    submit: "ยืนยัน",
    edit: "แก้ไข",
    editBan: "แก้ไขการแบน",
    editBanSuccess: "แก้ไขการแบนสำเร็จ !",
    editWarning: "แก้ไขการเตือน",
    editWarningSuccess: "แก้ไขการเตือนสำเร็จ !",
    profile: "โปรไฟล์",
    language: "ภาษา",
    logout: "ล็อกเอาท์",
    searchHint: "ค้นหา...",
    playtime: "ระยะเวลาที่เล่น:",
    lastSeen: "พบล่าสุด:",
    myPlaytime: "เวลาที่เล่นไปของคุณ",
    playtimeTitle: "ระยะเวลาการเล่น",
    staffPlaytime: "เวลาที่เล่นไปของสตาฟ",
    lookupPlayer: "ค้นหาผู้เล่น",
    lookupIssuer: "ค้นหาคนลงโทษ",
    reports: "การแจ้งผู้เล่น",
    warning: "การเตือน",
    ban: "แบน",
    report: "แจ้งผู้เล่น",
    cheaterReport: "แจ้งผู้ใช้แฮก",
    players: "ผู้เล่น",
    name: "ชื่อ",
    names: "ชื่อ",
    lastJoin: "เข้าครั้งล่าสุด",
    lastLeave: "ออกครั้งล่าสุด",
    firstJoin: "เข้าครั้งแรก",
    firstLeave: "ออกครั้งแรก",
    myServers: "เซิร์ฟเวอร์ของฉัน",
    viewSecret: "ดู Secret",
    changeName: "เปลี่ยนชื่อ",
    resetSecret: "รีเซ็ต Secret",
    viewSecretMsg1: "Secret ของเซิร์ฟเวอร์นี้อยู่ด้านล่าง โปรดเก็บไว้เป็นความลับและรีเซ็ตทันทีถ้าหากว่ามีคนอื่นได้มันไป",
    viewSecretMsg2: "ในการที่จะเชื่อมต่อเซิร์ฟเวอร์นี้กับเกมเซิร์ฟเวอร์ ให้ใส่คำสั่งนี้ไปในคอนโซลเซิร์ฟเวอร์:",
    changeNameNewName: "ชื่อใหม่",
    resetSecretMsg: "การที่รีเซ็ต Secret เชิร์ฟเวอร์นี้จะตัดการเชื่อมต่อกับเซิร์ฟเวอร์ปัจจุบัน โปรดเช็คให้มั่นใจว่าคุณใส่ Secret ใหม่หลังรีเซ็ต",
    changeNameSuccess: "เปลี่ยนชื่อสำเร็จ!",
    resetSecretSuccess: "รีเซ็ต Secret สำเร็จ!",
    createServer: "สร้างเซิร์ฟเวอร์",
    createServerMsg: "หลังจากที่คุณสร้างเซิร์ฟเวอร์ กดปุ่มดู Secret เพื่อที่จะเชื่อมต่อกับเกมเซิร์ฟเวอร์",
    createServerSuccess: "สร้างเซิร์ฟเวอร์สำเร็จ!",
    linkToDiscord: "เชื่อมต่อกับดิสคอร์ด",
    linkToDiscordMsg1: "ไอดีเซิร์ฟเวอร์นี้อยู่ด้านล่าง คุณสามารถใช้ไอดีเพื่อที่จะเชื่อมต่อเซิร์ฟเวอร์นี้กับเซิร์ฟเวอร์ดิสคอร์ดคุณได้",
    linkToDiscordMsg2: "ในการที่จะเชื่อมต่อเซิร์ฟเวอร์นี้กับเซิร์ฟเวอร์ดิสคอร์ด ให้ใส่คำสั่งนี้ไปในเซิร์ฟเวอร์ดิสคอร์ด:",
    linkToDiscordCmd: "/link serverid:",
}

export default TH;
